from typing import Tuple
from PIL import Image
from PIL.ExifTags import TAGS

class ExifScanner:

    # Common AI image generator software identifiers
    AI_GENERATOR_SIGNATURES = {
        'dalle', 'midjourney', 'stable diffusion', 'deepai',
        'neural', 'gan', 'artificial', 'synthesized', 'generated'
    }


    def is_photo(self, image):
        """
        Check if the given image contains any EXIF data
        
        Args:
            image: already lodaded image
        Returns:
            bool: True if image contains EXIF data, False otherwise
        """
        try:
            # Get EXIF data
            exif_data = image._getexif()
            
            # If there's no EXIF data, check for general image info
            if exif_data is None:
                # Check if image has any metadata
                image_info = image.info
                return len(image_info) > 0
                
            return True
                
        except Exception as e:
            print(f"Error processing image: {str(e)}")
            return False
    

    def check_image(self, image_path) -> Tuple[bool, str]:
        """
        Check if the image might be AI generated by analyzing its metadata
        
        Args:
            image_path: Path to the image file
            
        Returns:
            Tuple[bool, str]: (is_likely_ai_generated, reason)
        """
        try:
            with Image.open(image_path) as img:
                metadata = self.get_metadata(img)
                
                # Check for common indicators
                indicators = self._analyze_metadata(metadata)
                
                if not metadata:
                    return True, "No metadata found - possible AI generation or stripped metadata"
                    
                if indicators:
                    return True, f"Potential AI indicators found: {', '.join(indicators)}"
                
                return False, "No clear AI generation indicators found"
                
        except Exception as e:
            return None, f"Error analyzing image: {str(e)}"

    def _analyze_metadata(self, metadata: dict) -> list:
        """
        Analyze metadata for AI generation indicators
        
        Returns:
            list: List of found indicators
        """
        indicators = []
        
        # Check software information
        software = metadata.get('Software', '')
        if isinstance(software, str):
            software = software.lower()
            if any(sig in software for sig in self.AI_GENERATOR_SIGNATURES):
                indicators.append(f"AI software detected: {software}")

        # Check for artist/author information
        artist = metadata.get('Artist', '')
        if isinstance(artist, str) and any(sig in artist.lower() for sig in self.AI_GENERATOR_SIGNATURES):
            indicators.append(f"AI-related artist field: {artist}")

        # Check for common AI model metadata
        for key, value in metadata.items():
            if isinstance(value, str):
                value_lower = value.lower()
                if any(sig in value_lower for sig in self.AI_GENERATOR_SIGNATURES):
                    indicators.append(f"AI indicator in {key}: {value}")

        # Check for suspicious characteristics
        if 'MakerNote' in metadata:
            maker_note = str(metadata['MakerNote']).lower()
            if any(sig in maker_note for sig in self.AI_GENERATOR_SIGNATURES):
                indicators.append("AI signature in MakerNote")

        # Check for missing typical camera metadata
        if not any(key in metadata for key in [
            'Make', 'Model', 'ExifImageWidth', 'ExifImageHeight', 
            'DateTimeOriginal', 'ExposureTime', 'FNumber'
        ]):
            indicators.append("Missing typical camera metadata")

        return indicators

    def get_metadata(self, image) -> dict:
        """
        Extract all available metadata from the image
        
        Args:
            image: PIL Image object
            
        Returns:
            dict: Dictionary containing the metadata
        """
        metadata = {}
        
        try:
            # Get EXIF data
            exif_data = image._getexif()
            
            if exif_data:
                # Decode EXIF data
                for tag_id in exif_data:
                    tag = TAGS.get(tag_id, tag_id)
                    data = exif_data.get(tag_id)
                    metadata[tag] = data
            
            # Get general image info
            for key, value in image.info.items():
                if key not in metadata:
                    metadata[key] = value
                    
            # Add basic image properties
            metadata['format'] = image.format
            metadata['size'] = image.size
            metadata['mode'] = image.mode
                
        except Exception as e:
            print(f"Error extracting metadata: {str(e)}")
            
        return metadata

    # def get_metadata(self, image):
    #     """
    #     Extract all available metadata from the image
        
    #     Args:
    #         image: The image as PILImage
            
    #     Returns:
    #         dict: Dictionary containing the metadata
    #     """
    #     metadata = {}
        
    #     try:
    #         # Get EXIF data
    #         exif_data = image._getexif()
            
    #         if exif_data:
    #             # Decode EXIF data
    #             for tag_id in exif_data:
    #                 tag = TAGS.get(tag_id, tag_id)
    #                 data = exif_data.get(tag_id)
    #                 metadata[tag] = data
            
    #         # Get general image info
    #         for key, value in image.info.items():
    #             if key not in metadata:
    #                 metadata[key] = value
                    
    #         # Add basic image properties
    #         metadata['format'] = image.format
    #         metadata['size'] = image.size
    #         metadata['mode'] = image.mode
                
    #     except Exception as e:
    #         print(f"Error extracting metadata: {str(e)}")
            
    #     return metadata
