#!/usr/bin/env python3
"""
Image Evaluation Tool for Model Comparison

This tool allows you to view and rate images generated by different models,
grouped by prompt, image number, and resolution.
"""

import os
import json
import gradio as gr
from pathlib import Path
from typing import Dict, List, Tuple
from datetime import datetime
from dotenv import load_dotenv
import re
import atexit


class ImageEvaluator:
    def __init__(self, output_directory: str):
        self.output_dir = output_directory
        self.evaluations_file = os.path.join(output_directory, "evaluations.json")
        self.evaluations = self.load_evaluations()
        self.prompts = self.load_prompts()
        self.images_data = self.scan_images()
        
    def load_evaluations(self) -> Dict:
        """Load existing evaluations from JSON file"""
        if os.path.exists(self.evaluations_file):
            try:
                with open(self.evaluations_file, 'r') as f:
                    return json.load(f)
            except (json.JSONDecodeError, IOError) as e:
                print(f"Warning: Could not load evaluations: {e}")
        return {}
    
    def save_evaluations(self):
        """Save evaluations to JSON file"""
        try:
            with open(self.evaluations_file, 'w') as f:
                json.dump(self.evaluations, f, indent=2)
        except IOError as e:
            print(f"Error saving evaluations: {e}")
    
    def load_prompts(self) -> Dict[int, str]:
        """Load prompts from seeds.json (primary) or prompts.txt (fallback)"""
        prompts = {}
        seeds_file = os.path.join(self.output_dir, "seeds.json")
        prompts_file = os.path.join(self.output_dir, "prompts.txt")
        
        # Try seeds.json first
        if os.path.exists(seeds_file):
            try:
                with open(seeds_file, 'r', encoding='utf-8') as f:
                    seeds = json.load(f)
                    for key, value in seeds.items():
                        if isinstance(value, dict) and "prompt_text" in value:
                            try:
                                # Try to extract prompt number from key (e.g., "prompt_1" -> 1)
                                if key.startswith("prompt_"):
                                    prompt_num = int(key.split("_")[1])
                                    prompt_text = value.get("prompt_text", "")
                                    if prompt_text:
                                        prompts[prompt_num] = prompt_text
                            except Exception:
                                continue
                
                if prompts:
                    print(f"Loaded {len(prompts)} prompts from seeds.json")
                    return prompts
                else:
                    print(f"seeds.json found but no prompts extracted, falling back to prompts.txt")
            except Exception as e:
                print(f"Error loading seeds.json: {e}, falling back to prompts.txt")
        
        # Fallback: prompts.txt
        if os.path.exists(prompts_file):
            try:
                with open(prompts_file, 'r', encoding='utf-8') as f:
                    lines = f.readlines()
                    prompt_num = 1
                    for line in lines:
                        line = line.strip()
                        if not line:
                            continue
                        # Check if line has format "num - prompt" or just "prompt"
                        match = re.match(r'(\d+)\s*-\s*(.+)', line)
                        if match:
                            prompt_num = int(match.group(1))
                            prompt_text = match.group(2)
                        else:
                            # Line is just the prompt text without number
                            prompt_text = line
                        
                        prompts[prompt_num] = prompt_text
                        prompt_num += 1  # Auto-increment for next line if no number given
                
                if prompts:
                    print(f"Loaded {len(prompts)} prompts from prompts.txt")
                    return prompts
            except Exception as e:
                print(f"Error loading prompts.txt: {e}")
        
        print(f"Warning: Neither seeds.json nor prompts.txt found in {self.output_dir}")
        return prompts
    
    def parse_filename(self, filename: str) -> Dict:
        """
        Parse filename like: M01-P1-I1_modelname-512x512-20260203_120000.jpg
        Returns: {model_num, prompt_num, image_num, model_name, width, height, timestamp}
        """
        pattern = r'M(\d+)-P(\d+)-I(\d+)_(.+?)-(\d+)x(\d+)-(\d+_\d+)\.jpg'
        match = re.match(pattern, filename)
        
        if match:
            return {
                'model_num': int(match.group(1)),
                'prompt_num': int(match.group(2)),
                'image_num': int(match.group(3)),
                'model_name': match.group(4),
                'width': int(match.group(5)),
                'height': int(match.group(6)),
                'timestamp': match.group(7),
                'resolution': f"{match.group(5)}x{match.group(6)}"
            }
        return None
    
    def scan_images(self) -> Dict:
        """Scan output directory and all subfolders for images, organize by prompt, image_num, and resolution"""
        images = {}
        
        if not os.path.exists(self.output_dir):
            print(f"Output directory not found: {self.output_dir}")
            return images
        
        for root, dirs, files in os.walk(self.output_dir):
            for filename in files:
                if not filename.endswith('.jpg'):
                    continue
                parsed = self.parse_filename(filename)
                if not parsed:
                    continue
                # Create nested structure: prompt -> image_num -> resolution -> [models]
                p = parsed['prompt_num']
                i = parsed['image_num']
                r = parsed['resolution']
                if p not in images:
                    images[p] = {}
                if i not in images[p]:
                    images[p][i] = {}
                if r not in images[p][i]:
                    images[p][i][r] = []
                images[p][i][r].append({
                    'filepath': os.path.join(root, filename),
                    'model_num': parsed['model_num'],
                    'model_name': parsed['model_name'],
                    'filename': filename
                })
        # Sort models by model_num within each group
        for p in images:
            for i in images[p]:
                for r in images[p][i]:
                    images[p][i][r].sort(key=lambda x: x['model_num'])
        return images
    
    def get_prompts(self) -> List[str]:
        """Get list of available prompts"""
        if not self.images_data:
            return []
        return sorted([f"Prompt {p}" for p in self.images_data.keys()])
    
    def get_prompt_text(self, prompt_num: int) -> str:
        """Get the text for a specific prompt number"""
        return self.prompts.get(prompt_num, "Prompt text not found")
    
    def get_image_numbers(self, prompt_num: int) -> List[str]:
        """Get list of image numbers for a prompt"""
        if prompt_num not in self.images_data:
            return []
        return sorted([f"Image {i}" for i in self.images_data[prompt_num].keys()])
    
    def get_resolutions(self, prompt_num: int, image_num: int) -> List[str]:
        """Get list of resolutions for a prompt and image number"""
        if prompt_num not in self.images_data or image_num not in self.images_data[prompt_num]:
            return []
        return sorted(self.images_data[prompt_num][image_num].keys())
    
    def get_images_for_group(self, prompt_num: int, image_num: int, resolution: str) -> List[Tuple]:
        """Get all images for a specific prompt, image_num, and resolution"""
        if (prompt_num not in self.images_data or 
            image_num not in self.images_data[prompt_num] or
            resolution not in self.images_data[prompt_num][image_num]):
            return []
        
        images = self.images_data[prompt_num][image_num][resolution]
        result = []
        
        for img in images:
            rating = self.evaluations.get(img['filename'], {}).get('rating', 0)
            label = f"{img['model_name']} (M{img['model_num']:02d})"
            if rating > 0:
                label += f" ⭐{rating}"
            result.append((img['filepath'], label))
        
        return result
    
    def get_model_names_for_group(self, prompt_num: int, image_num: int, resolution: str) -> List[str]:
        """Get list of model names in order for a specific group"""
        if (prompt_num not in self.images_data or 
            image_num not in self.images_data[prompt_num] or
            resolution not in self.images_data[prompt_num][image_num]):
            return []
        
        images = self.images_data[prompt_num][image_num][resolution]
        return [img['model_name'] for img in images]
    
    def save_rating(self, prompt_str: str, image_str: str, resolution: str, 
                    model_name: str, rating: int) -> str:
        """Save a rating for a specific image"""
        if not prompt_str or not image_str or not resolution or not model_name:
            return "❌ Please select all filters first"
        
        if rating < 1 or rating > 5:
            return "❌ Rating must be between 1 and 5"
        
        prompt_num = int(prompt_str.split()[-1])
        image_num = int(image_str.split()[-1])
        
        # Find the image
        if (prompt_num not in self.images_data or 
            image_num not in self.images_data[prompt_num] or
            resolution not in self.images_data[prompt_num][image_num]):
            return "❌ No images found for this combination"
        
        images = self.images_data[prompt_num][image_num][resolution]
        target_image = None
        
        for img in images:
            if model_name in img['filename']:
                target_image = img
                break
        
        if not target_image:
            return f"❌ Model '{model_name}' not found"
        
        # Save rating
        filename = target_image['filename']
        if filename not in self.evaluations:
            self.evaluations[filename] = {}
        
        self.evaluations[filename] = {
            'rating': rating,
            'timestamp': datetime.now().isoformat(),
            'prompt_num': prompt_num,
            'image_num': image_num,
            'resolution': resolution,
            'model_name': target_image['model_name']
        }
        
        self.save_evaluations()
        return f"✅ Saved rating {rating}⭐ for {target_image['model_name']}"
    
    def get_statistics(self) -> str:
        """Generate statistics about ratings"""
        if not self.evaluations:
            return "No ratings yet"
        
        model_ratings = {}
        for filename, data in self.evaluations.items():
            model = data.get('model_name', 'Unknown')
            rating = data.get('rating', 0)
            
            if model not in model_ratings:
                model_ratings[model] = []
            model_ratings[model].append(rating)
        
        stats = "📊 **Rating Statistics**\n\n"
        stats += f"Total rated images: {len(self.evaluations)}\n\n"
        
        # Calculate averages
        model_averages = []
        for model, ratings in model_ratings.items():
            avg = sum(ratings) / len(ratings)
            model_averages.append((model, avg, len(ratings)))
        
        # Sort by average rating (descending)
        model_averages.sort(key=lambda x: x[1], reverse=True)
        
        stats += "**Average Ratings by Model:**\n"
        for model, avg, count in model_averages:
            stars = "⭐" * int(round(avg))
            stats += f"- {model}: {avg:.2f} {stars} ({count} ratings)\n"
        
        return stats


def create_ui(evaluator: ImageEvaluator):
    """Create Gradio UI"""
    
    with gr.Blocks(title="Image Evaluation Tool") as demo:
        gr.Markdown("# 🎨 Image Evaluation Tool")
        gr.Markdown("Compare and rate images generated by different models")
        
        with gr.Row():
            with gr.Column(scale=1):
                gr.Markdown("### Filters")
                prompt_dropdown = gr.Dropdown(
                    choices=evaluator.get_prompts(),
                    label="Select Prompt",
                    interactive=True
                )
                prompt_display = gr.Textbox(
                    label="Prompt Text",
                    interactive=False,
                    lines=3,
                    placeholder="Select a prompt to view its text"
                )
                image_dropdown = gr.Dropdown(
                    label="Select Image Number",
                    interactive=True
                )
                resolution_dropdown = gr.Dropdown(
                    label="Select Resolution",
                    interactive=True
                )
                
                load_btn = gr.Button("🔄 Load Images", variant="primary")
                
                gr.Markdown("---")
                gr.Markdown("### Rate Selected Image")
                
                model_select = gr.Dropdown(
                    label="Select Model to Rate",
                    interactive=True,
                    value="",
                    allow_custom_value=True
                )
                rating_slider = gr.Slider(
                    minimum=1, maximum=5, step=1, value=3,
                    label="Rating (1-5 stars)"
                )
                save_btn = gr.Button("💾 Save Rating", variant="secondary")
                status_text = gr.Textbox(label="Status", interactive=False)
                
                gr.Markdown("---")
                stats_btn = gr.Button("📊 Show Statistics")
                
            with gr.Column(scale=3):
                gr.Markdown("### Image Comparison")
                info_text = gr.Markdown("Select filters and click 'Load Images'")
                gallery = gr.Gallery(
                    label="Models Comparison",
                    columns=3,
                    height="auto",
                    object_fit="contain"
                )
        
        with gr.Row():
            stats_output = gr.Markdown()
        
        # Event handlers
        def update_prompt_text(prompt_str):
            if not prompt_str:
                return ""
            prompt_num = int(prompt_str.split()[-1])
            return evaluator.get_prompt_text(prompt_num)
        
        def update_image_dropdown(prompt_str):
            if not prompt_str:
                return gr.update(choices=[], value="")
            prompt_num = int(prompt_str.split()[-1])
            choices = evaluator.get_image_numbers(prompt_num)
            return gr.update(choices=choices, value="" if not choices else choices[0])
        
        def update_resolution_dropdown(prompt_str, image_str):
            if not prompt_str or not image_str:
                return gr.update(choices=[], value="")
            prompt_num = int(prompt_str.split()[-1])
            image_num = int(image_str.split()[-1])
            choices = evaluator.get_resolutions(prompt_num, image_num)
            return gr.update(choices=choices, value="" if not choices else choices[0])
        
        def load_images(prompt_str, image_str, resolution):
            if not prompt_str or not image_str or not resolution:
                return [], "❌ Please select all filters", gr.update(choices=[])
            
            prompt_num = int(prompt_str.split()[-1])
            image_num = int(image_str.split()[-1])
            images = evaluator.get_images_for_group(prompt_num, image_num, resolution)
            
            if not images:
                return [], "❌ No images found", gr.update(choices=[])
            
            info = f"**Showing:** {prompt_str} | {image_str} | {resolution} | {len(images)} models"
            model_choices = [label.split(" (M")[0] for _, label in images]
            
            return images, info, gr.update(choices=model_choices, value=model_choices[0] if model_choices else "")
        
        def save_rating_handler(prompt_str, image_str, resolution, model_name, rating):
            status = evaluator.save_rating(prompt_str, image_str, resolution, model_name, int(rating))
            
            # Reload images to show updated ratings
            if prompt_str and image_str and resolution:
                prompt_num = int(prompt_str.split()[-1])
                image_num = int(image_str.split()[-1])
                images = evaluator.get_images_for_group(prompt_num, image_num, resolution)
                model_choices = [label.split(" (M")[0] for _, label in images]
                return status, images, gr.update(choices=model_choices, value=model_name if model_name in model_choices else "")
            
            return status, [], gr.update(choices=[])
        
        # Connect events
        prompt_dropdown.change(
            update_prompt_text,
            inputs=[prompt_dropdown],
            outputs=[prompt_display]
        )
        
        prompt_dropdown.change(
            update_image_dropdown,
            inputs=[prompt_dropdown],
            outputs=[image_dropdown]
        )
        
        image_dropdown.change(
            update_resolution_dropdown,
            inputs=[prompt_dropdown, image_dropdown],
            outputs=[resolution_dropdown]
        )
        
        # Auto-load images when resolution is selected
        resolution_dropdown.change(
            load_images,
            inputs=[prompt_dropdown, image_dropdown, resolution_dropdown],
            outputs=[gallery, info_text, model_select]
        )
        
        # Handle gallery image selection - set model name automatically
        def on_gallery_select(evt: gr.SelectData, prompt_str, image_str, resolution):
            """When an image is clicked, set the corresponding model name"""
            if not prompt_str or not image_str or not resolution:
                return ""
            
            prompt_num = int(prompt_str.split()[-1])
            image_num = int(image_str.split()[-1])
            model_names = evaluator.get_model_names_for_group(prompt_num, image_num, resolution)
            
            if evt.index is not None and 0 <= evt.index < len(model_names):
                return model_names[evt.index]
            return ""
        
        gallery.select(
            on_gallery_select,
            inputs=[prompt_dropdown, image_dropdown, resolution_dropdown],
            outputs=[model_select]
        )
        
        load_btn.click(
            load_images,
            inputs=[prompt_dropdown, image_dropdown, resolution_dropdown],
            outputs=[gallery, info_text, model_select]
        )
        
        save_btn.click(
            save_rating_handler,
            inputs=[prompt_dropdown, image_dropdown, resolution_dropdown, model_select, rating_slider],
            outputs=[status_text, gallery, model_select]
        )
        
        stats_btn.click(
            evaluator.get_statistics,
            outputs=[stats_output]
        )
    
    return demo


def main():
    import argparse
    import sys
    
    # Set UTF-8 encoding for console output on Windows
    if sys.platform == 'win32':
        try:
            import io
            sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
            sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8')
        except Exception:
            pass
    
    # Load .env file first
    load_dotenv(override=True)
    
    parser = argparse.ArgumentParser(description="Image Evaluation Tool")
    parser.add_argument(
        '--output-dir',
        type=str,
        default=None,
        help='Directory containing generated images (default: from .env OUTPUT_DIRECTORY or ./output)'
    )
    parser.add_argument(
        '--port',
        type=int,
        default=7860,
        help='Port for web interface (default: 7860)'
    )
    parser.add_argument(
        '--share',
        action='store_true',
        help='Create a public link'
    )
    
    args = parser.parse_args()
    
    # Determine output directory
    if args.output_dir:
        output_base = args.output_dir
    else:
        output_base = os.getenv('OUTPUT_DIRECTORY', './output')
    
    # Find the most recent output directory if a timestamped one exists
    if os.path.exists(output_base):
        subdirs = [d for d in os.listdir(output_base) 
                   if os.path.isdir(os.path.join(output_base, d)) and 
                   re.match(r'\d{8}_\d{4}', d)]
        if subdirs:
            latest_dir = sorted(subdirs)[-1]
            output_dir = os.path.join(output_base, latest_dir)
            print(f"Using latest output directory: {output_dir}")
        else:
            output_dir = output_base
    else:
        output_dir = output_base
        print(f"Output directory not found: {output_dir}")
        print("Please run check_models.py first or specify correct --output-dir")
        return
    
    evaluator = ImageEvaluator(output_dir)
    
    if not evaluator.images_data:
        print("❌ No images found in output directory!")
        print(f"   Directory: {output_dir}")
        print("   Please run check_models.py first to generate images.")
        return
    
    total_images = sum(
        len(models)
        for p in evaluator.images_data.values()
        for i in p.values()
        for r, models in i.items()
    )
    
    print(f"✅ Found {total_images} images across:")
    print(f"   - {len(evaluator.images_data)} prompts")
    print(f"   - {len(evaluator.evaluations)} rated images")
    
    # Register exit handler to print statistics before closing
    def print_final_statistics():
        print("\n" + "="*60)
        print("📊 FINAL STATISTICS")
        print("="*60)
        stats = evaluator.get_statistics()
        print(stats)
        print("="*60 + "\n")
    
    atexit.register(print_final_statistics)
    
    demo = create_ui(evaluator)
    demo.launch(
        server_name="0.0.0.0",
        server_port=args.port,
        share=args.share,
        theme=gr.themes.Soft()
    )


if __name__ == "__main__":
    main()
